# Generated by Django 5.2.1 on 2025-06-05 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='time',
            field=models.IntegerField(null=True),
        ),
    ]
