# Generated by Django 5.2.1 on 2025-06-07 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_lesson_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
