# Generated by Django 5.2.1 on 2025-06-09 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_lessonprogress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessonprogress',
            old_name='course',
            new_name='lesson',
        ),
    ]
